/**
 * Materialises the aggregator snapshots for the site's previews, the way the
 * shadcn CLI would install them into an app: components/external/<library>/,
 * the upstream demos next to them, their CSS in app/external.css and a lazy
 * preview map. Offline and deterministic; `--check` fails when the committed
 * output is stale or the site lacks a package an item needs.
 */
import { mkdir, readFile, rm, writeFile, readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { loadExternal } from "../lib/external";
import { cssText, materializedPath, noticeHeader, rewriteImports, dependenciesOf } from "../lib/upstreams";

const check = process.argv.includes("--check");
const libraries = loadExternal();
const out = new Map<string, string>();

/** Fabrials-written previews for upstreams that publish no demos. */
const ownDemos = new Set(
  (await readdir("components/external-demos").catch(() => [] as string[])).map((file) => file.replace(/\.tsx$/, "")),
);

function exportedComponent(source: string): string {
  if (/export\s+default\s/.test(source)) return "default";
  const named = /export\s+(?:function|const)\s+([A-Z]\w*)/.exec(source);
  if (!named) throw new Error("A demo exports no component");
  return named[1]!;
}

const previews: string[] = [];
const theme: string[] = [];
const rules: string[] = [];
const needed = new Map<string, string>();

for (const { snapshot, licenseText, items } of libraries) {
  for (const { slug, item, raw, demo } of items) {
    const header = noticeHeader(item.title, snapshot, licenseText);
    for (const file of raw.files) {
      const body = rewriteImports(file.content, snapshot.name);
      const content = /^["']use client["'];?\n/.test(body) ? body.replace(/^(["']use client["'];?\n)/, `$1${header}`) : header + body;
      out.set(join("components/external", snapshot.name, materializedPath(file)), content);
    }
    for (const [name, value] of Object.entries(raw.cssVars?.theme ?? {})) theme.push(`  --${name}: ${value};`);
    if (raw.css && Object.keys(raw.css).length) rules.push(`/* ${snapshot.title}: ${item.title} */\n${cssText(raw.css)}`);
    for (const dep of item.dependencies) needed.set(dep.name, dep.version);
    if (item.hidden) continue;
    if (demo) {
      const file = demo.files[0]!;
      const path = join("components/external", snapshot.name, "demos", `${item.demo!.name}.tsx`);
      const body = rewriteImports(file.content, snapshot.name);
      out.set(path, (body.startsWith('"use client"') ? "" : '"use client";\n') + noticeHeader(`${item.title} demo`, snapshot, licenseText) + body);
      for (const dep of dependenciesOf(demo)) needed.set(dep.name, needed.get(dep.name) ?? "latest");
      const name = exportedComponent(body);
      const demoModule = `./${snapshot.name}/demos/${item.demo!.name}`;
      previews.push(`  "${slug}": dynamic(() => import("${demoModule}")${name === "default" ? "" : `.then((m) => m.${name})`}),`);
    } else if (ownDemos.has(slug)) {
      previews.push(`  "${slug}": dynamic(() => import("../external-demos/${slug}")),`);
    }
  }
}

out.set(
  "components/external/previews.tsx",
  `"use client";
// Generated by scripts/generate-external.ts. Previews load on the page that shows them.
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

export const externalPreviews: Record<string, ComponentType> = {
${previews.sort().join("\n")}
};
`,
);
out.set(
  "app/external.css",
  `/* Generated by scripts/generate-external.ts: the CSS third-party components ask shadcn to add. */
@theme inline {
${[...new Set(theme)].sort().join("\n")}
}

${rules.join("\n\n")}
`,
);

const site = JSON.parse(await readFile("package.json", "utf8")) as { dependencies: Record<string, string> };
const missing = [...needed].filter(([name]) => !site.dependencies[name]).map(([name, version]) => `${name}@^${version}`);
if (missing.length) {
  console.error(`The site needs these packages for previews: bun add ${missing.join(" ")}`);
  process.exit(1);
}

const stale: string[] = [];
for (const [path, content] of out) {
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === content) continue;
  if (check) stale.push(path);
  else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }
}
async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  return (await Promise.all(entries.map((e) => (e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)])))).flat();
}
for (const path of await walk("components/external"))
  if (!out.has(path)) {
    if (check) stale.push(path);
    else await rm(path);
  }
if (stale.length) {
  console.error(`External components are out of date (run bun run registry:external):\n${stale.join("\n")}`);
  process.exit(1);
}
console.log(`${check ? "Checked" : "Wrote"} ${out.size} files for ${libraries.length} libraries.`);
