// Generated by scripts/generate-external.ts from registry/external/. Data only, safe on the client.
export type ExternalIndexLibrary = {
  name: string;
  title: string;
  homepage: string;
  repository: string;
  description: string;
  tier: "fabrials" | "community";
  license: string;
  commit: string;
  fetchedAt: string;
  items: { slug: string; name: string; title: string; description: string; conformance: string[] }[];
};

export const externalIndex: ExternalIndexLibrary[] = [
  {
    "name": "kibo",
    "title": "Kibo UI",
    "homepage": "https://www.kibo-ui.com",
    "repository": "haydenbleasel/kibo",
    "description": "Larger, composable pieces for product interfaces: boards, uploads, calendars and more.",
    "tier": "community",
    "license": "MIT",
    "commit": "3d63cdb15b79d972e3dc38a10997987672f9b263",
    "fetchedAt": "2026-09-27",
    "items": [
      {
        "slug": "kibo-contribution-graph",
        "name": "contribution-graph",
        "title": "Contribution Graph",
        "description": "A GitHub-style contribution graph component that displays activity levels over time.",
        "conformance": []
      },
      {
        "slug": "kibo-dropzone",
        "name": "dropzone",
        "title": "Dropzone",
        "description": "Allows users to drag-and-drop files into a container to upload or process them.",
        "conformance": []
      },
      {
        "slug": "kibo-kanban",
        "name": "kanban",
        "title": "Kanban",
        "description": "A kanban board is a visual tool that helps you manage and visualize your work. It is a board with columns, and each column represents a status, e.g. \"Backlog\", \"In Progress\", \"Done\".",
        "conformance": []
      },
      {
        "slug": "kibo-rating",
        "name": "rating",
        "title": "Rating",
        "description": "A star rating component with keyboard navigation and hover effects.",
        "conformance": []
      }
    ]
  },
  {
    "name": "magicui",
    "title": "Magic UI",
    "homepage": "https://magicui.design",
    "repository": "magicuidesign/magicui",
    "description": "Animated components and effects for landing pages, built on Tailwind and Motion.",
    "tier": "community",
    "license": "MIT",
    "commit": "d7207e5692d14c00dceafa8488d6d01f197fa0e4",
    "fetchedAt": "2026-09-27",
    "items": [
      {
        "slug": "magicui-animated-list",
        "name": "animated-list",
        "title": "Animated List",
        "description": "A list that animates each item in sequence with a delay. Used to showcase notifications or events on your landing page.",
        "conformance": [
          "ignores-reduced-motion"
        ]
      },
      {
        "slug": "magicui-dot-pattern",
        "name": "dot-pattern",
        "title": "Dot Pattern",
        "description": "A background dot pattern made with SVGs, fully customizable using Tailwind CSS.",
        "conformance": [
          "literal-colours",
          "continuous-motion",
          "ignores-reduced-motion"
        ]
      },
      {
        "slug": "magicui-file-tree",
        "name": "file-tree",
        "title": "File Tree",
        "description": "A component used to showcase the folder and file structure of a directory.",
        "conformance": [
          "literal-colours",
          "ignores-reduced-motion"
        ]
      },
      {
        "slug": "magicui-marquee",
        "name": "marquee",
        "title": "Marquee",
        "description": "An infinite scrolling component that can be used to display text, images, or videos.",
        "conformance": [
          "continuous-motion",
          "ignores-reduced-motion"
        ]
      },
      {
        "slug": "magicui-terminal",
        "name": "terminal",
        "title": "Terminal",
        "description": "A terminal component",
        "conformance": [
          "literal-colours",
          "ignores-reduced-motion"
        ]
      }
    ]
  }
];
