// Generated by scripts/generate-shims.ts. The shadcn primitives ui.fabrials.com installs as Fabrials shims.
export const shimIndex: { name: string; exports: string[] }[] = [
  {
    "name": "accordion",
    "exports": [
      "Accordion",
      "AccordionContent",
      "AccordionItem",
      "AccordionTrigger"
    ]
  },
  {
    "name": "alert",
    "exports": [
      "Alert",
      "AlertAction",
      "AlertDescription",
      "AlertTitle"
    ]
  },
  {
    "name": "alert-dialog",
    "exports": [
      "AlertDialog",
      "AlertDialogAction",
      "AlertDialogCancel",
      "AlertDialogContent",
      "AlertDialogDescription",
      "AlertDialogFooter",
      "AlertDialogHeader",
      "AlertDialogMedia",
      "AlertDialogOverlay",
      "AlertDialogPortal",
      "AlertDialogTitle",
      "AlertDialogTrigger"
    ]
  },
  {
    "name": "breadcrumb",
    "exports": [
      "Breadcrumb",
      "BreadcrumbEllipsis",
      "BreadcrumbItem",
      "BreadcrumbLink",
      "BreadcrumbList",
      "BreadcrumbPage",
      "BreadcrumbSeparator"
    ]
  },
  {
    "name": "button",
    "exports": [
      "Button",
      "buttonVariants"
    ]
  },
  {
    "name": "button-group",
    "exports": [
      "ButtonGroup",
      "ButtonGroupSeparator",
      "ButtonGroupText",
      "buttonGroupVariants"
    ]
  },
  {
    "name": "card",
    "exports": [
      "Card",
      "CardAction",
      "CardContent",
      "CardDescription",
      "CardFooter",
      "CardHeader",
      "CardTitle"
    ]
  },
  {
    "name": "carousel",
    "exports": [
      "Carousel",
      "CarouselContent",
      "CarouselItem",
      "CarouselNext",
      "CarouselPrevious",
      "useCarousel"
    ]
  },
  {
    "name": "checkbox",
    "exports": [
      "Checkbox"
    ]
  },
  {
    "name": "collapsible",
    "exports": [
      "Collapsible",
      "CollapsibleContent",
      "CollapsibleTrigger"
    ]
  },
  {
    "name": "command",
    "exports": [
      "Command",
      "CommandDialog",
      "CommandEmpty",
      "CommandGroup",
      "CommandInput",
      "CommandItem",
      "CommandList",
      "CommandSeparator",
      "CommandShortcut"
    ]
  },
  {
    "name": "dialog",
    "exports": [
      "Dialog",
      "DialogClose",
      "DialogContent",
      "DialogDescription",
      "DialogFooter",
      "DialogHeader",
      "DialogOverlay",
      "DialogPortal",
      "DialogTitle",
      "DialogTrigger"
    ]
  },
  {
    "name": "dropdown-menu",
    "exports": [
      "DropdownMenu",
      "DropdownMenuCheckboxItem",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuLabel",
      "DropdownMenuPortal",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubContent",
      "DropdownMenuSubTrigger",
      "DropdownMenuTrigger"
    ]
  },
  {
    "name": "hover-card",
    "exports": [
      "HoverCard",
      "HoverCardContent",
      "HoverCardTrigger"
    ]
  },
  {
    "name": "input",
    "exports": [
      "Input"
    ]
  },
  {
    "name": "input-group",
    "exports": [
      "InputGroup",
      "InputGroupAddon",
      "InputGroupButton",
      "InputGroupInput",
      "InputGroupText",
      "InputGroupTextarea"
    ]
  },
  {
    "name": "kbd",
    "exports": [
      "Kbd",
      "KbdGroup"
    ]
  },
  {
    "name": "label",
    "exports": [
      "Label"
    ]
  },
  {
    "name": "native-select",
    "exports": [
      "NativeSelect",
      "NativeSelectOptGroup",
      "NativeSelectOption"
    ]
  },
  {
    "name": "navigation-menu",
    "exports": [
      "NavigationMenu",
      "NavigationMenuContent",
      "NavigationMenuIndicator",
      "NavigationMenuItem",
      "NavigationMenuLink",
      "NavigationMenuList",
      "NavigationMenuPositioner",
      "NavigationMenuTrigger",
      "navigationMenuTriggerStyle"
    ]
  },
  {
    "name": "pagination",
    "exports": [
      "Pagination",
      "PaginationContent",
      "PaginationEllipsis",
      "PaginationItem",
      "PaginationLink",
      "PaginationNext",
      "PaginationPrevious"
    ]
  },
  {
    "name": "popover",
    "exports": [
      "Popover",
      "PopoverContent",
      "PopoverDescription",
      "PopoverHeader",
      "PopoverTitle",
      "PopoverTrigger"
    ]
  },
  {
    "name": "radio-group",
    "exports": [
      "RadioGroup",
      "RadioGroupItem"
    ]
  },
  {
    "name": "scroll-area",
    "exports": [
      "ScrollArea",
      "ScrollBar"
    ]
  },
  {
    "name": "select",
    "exports": [
      "Select",
      "SelectContent",
      "SelectGroup",
      "SelectItem",
      "SelectLabel",
      "SelectScrollDownButton",
      "SelectScrollUpButton",
      "SelectSeparator",
      "SelectTrigger",
      "SelectValue"
    ]
  },
  {
    "name": "separator",
    "exports": [
      "Separator"
    ]
  },
  {
    "name": "sheet",
    "exports": [
      "Sheet",
      "SheetClose",
      "SheetContent",
      "SheetDescription",
      "SheetFooter",
      "SheetHeader",
      "SheetTitle",
      "SheetTrigger"
    ]
  },
  {
    "name": "sidebar",
    "exports": [
      "Sidebar",
      "SidebarContent",
      "SidebarFooter",
      "SidebarGroup",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarGroupLabel",
      "SidebarHeader",
      "SidebarInput",
      "SidebarInset",
      "SidebarMenu",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuButton",
      "SidebarMenuItem",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubButton",
      "SidebarMenuSubItem",
      "SidebarProvider",
      "SidebarRail",
      "SidebarSeparator",
      "SidebarTrigger",
      "useSidebar"
    ]
  },
  {
    "name": "skeleton",
    "exports": [
      "Skeleton"
    ]
  },
  {
    "name": "sonner",
    "exports": [
      "Toaster"
    ]
  },
  {
    "name": "spinner",
    "exports": [
      "Spinner"
    ]
  },
  {
    "name": "switch",
    "exports": [
      "Switch"
    ]
  },
  {
    "name": "table",
    "exports": [
      "Table",
      "TableBody",
      "TableCaption",
      "TableCell",
      "TableFooter",
      "TableHead",
      "TableHeader",
      "TableRow"
    ]
  },
  {
    "name": "textarea",
    "exports": [
      "Textarea"
    ]
  },
  {
    "name": "toggle-group",
    "exports": [
      "ToggleGroup",
      "ToggleGroupItem"
    ]
  },
  {
    "name": "tooltip",
    "exports": [
      "Tooltip",
      "TooltipContent",
      "TooltipProvider",
      "TooltipTrigger"
    ]
  }
];
