export type UiGroup =
  | "Brand"
  | "Controls"
  | "Overlays"
  | "Collections"
  | "Navigation"
  | "Composition"
  | "Metrics"
  | "Patterns"
  | "Documentation"
  | "Effects"
  | "AI chat"
  | "AI providers";

export type UiPackage = "@fabrials/ui" | "@fabrials/ai-ui";

export interface UiCatalogItem {
  slug: string;
  title: string;
  group: UiGroup;
  description: string;
  exports: string[];
  props: [string, string, string][];
  note: string;
  usage: string;
  package: UiPackage;
}

export const uiGroups: { name: UiGroup; description: string }[] = [
  {
    name: "Brand",
    description: "The dithered Highstorm light and the product marks. Landings, sign-in and product marks use them.",
  },
  {
    name: "Controls",
    description: "Buttons, fields and choices used across Fabrials products.",
  },
  {
    name: "Overlays",
    description: "Dialogs, menus and previews that keep keyboard focus.",
  },
  {
    name: "Collections",
    description: "Tables, tabs and other ways to scan a set of records.",
  },
  {
    name: "Navigation",
    description: "Shells, menus and the command palette.",
  },
  {
    name: "Composition",
    description: "Groups, loading and motion used inside a task.",
  },
  {
    name: "Metrics",
    description: "Totals and series drawn from real usage data.",
  },
  {
    name: "Patterns",
    description: "Page structure shared by operational screens.",
  },
  {
    name: "Documentation",
    description: "Code samples, install commands, file trees and repository links for docs and READMEs.",
  },
  {
    name: "Effects",
    description: "Decorative moonlight for sign-in and landing pages only.",
  },
  {
    name: "AI chat",
    description: "Presentational chat pieces from @fabrials/ai-ui. The host supplies the data.",
  },
  {
    name: "AI providers",
    description: "Provider marks and account presentation from @fabrials/ai-ui.",
  },
];

function ui(
  slug: string,
  title: string,
  group: UiGroup,
  description: string,
  exports: string[],
  props: UiCatalogItem["props"],
  note: string,
  pkg: UiPackage = "@fabrials/ui",
): UiCatalogItem {
  return {
    slug,
    title,
    group,
    description,
    exports,
    props,
    note,
    usage:
      pkg === "@fabrials/ai-ui"
        ? `import { ${exports.join(", ")} } from "${pkg}";\nimport "@fabrials/ai-ui/styles.css";`
        : `import { ${exports.join(", ")} } from "${pkg}";`,
    package: pkg,
  };
}

function aiUi(
  slug: string,
  title: string,
  description: string,
  exports: string[],
  props: UiCatalogItem["props"],
  note: string,
): UiCatalogItem {
  const group = slug === "provider-icon" ? "AI providers" : "AI chat";
  return ui(slug, title, group, description, exports, props, note, "@fabrials/ai-ui");
}

export const uiCatalog: UiCatalogItem[] = [
  ui(
    "button",
    "Button",
    "Controls",
    "The action control. One primary action per task, with quiet alternatives.",
    ["Button"],
    [
      ["variant", "default | accent | outline | secondary | ghost | destructive | link", "Visual weight of the action. default is ink, the primary; accent (Stormlight) only when one action must stand out."],
      ["disabled", "boolean", "Unavailable actions stay visible and unnamed as the next step."],
      ["type", "button | submit | reset", "Use submit inside a form."],
    ],
    "Standard controls are 40px. Compact density is a composition option on the parent, not a second button size.",
  ),
  ui(
    "icon-button",
    "Icon button",
    "Controls",
    "An icon-only button that always has a name: 44px, a tooltip on hover and on keyboard focus, an optional shortcut.",
    ["IconButton"],
    [
      ["label", "string", "The name: aria-label, or a hidden text node with textName. Required, because an icon is not a name."],
      ["tooltip", "boolean | ReactNode", "Repeats the name for sighted people. true by default; false leaves it out; a node replaces the text."],
      ["shortcut", "string | string[] | { keys, sequence?, separator? }", "Keys shown as flat Kbds in the tooltip and exposed as aria-keyshortcuts (\"⌘\" is Meta, \"Esc\" is Escape). { keys: [\"g\", \"i\"], sequence: true } is pressed one after the other: the tooltip says \"g then i\" and no aria-keyshortcuts is set, because it cannot express steps."],
      ["textName", "boolean", "Names the button with a visually hidden text node instead of aria-label, for toolbars whose tests or voice control read textContent."],
      ["size", "icon | icon-sm | icon-xs | icon-lg", "icon-lg (44px) by default; every size is 44px on touch."],
      ["variant", "Button variants", "ghost by default."],
      ["loading", "boolean", "Swaps the icon for the spinner and blocks repeated presses."],
    ],
    "Do not add title: the tooltip already repeats the name. It spreads its props on the Button, so a Base UI trigger can render it: <DropdownMenuTrigger render={<IconButton label=\"More\">…</IconButton>} />. The tooltip wrapper stays mounted when the button is disabled.",
  ),
  ui(
    "file-input",
    "File input",
    "Controls",
    "A file picker that is a button, with the chosen name, a clear action, a description and an error.",
    ["FileInput"],
    [
      ["label", "ReactNode", "The visible text of the button, in the interface's language. The browser's own \"Choose File\" is never shown."],
      ["name / accept / multiple / required / disabled / onChange / ref", "input props", "Go to the real input, so the form works as usual."],
      ["className / buttonClassName", "string", "The wrapper, and the button itself."],
      ["onFilesChange", "(files: File[]) => void", "Called with the chosen files."],
      ["fileName", "ReactNode | null", "The text beside the button. By default the names of the chosen files; pass a node to say something else and null to show nothing."],
      ["onClear / clearLabel", "() => void / string", "Adds a clear button while a name shows. The picker is emptied, so the same file can be chosen again, and focus returns to it."],
      ["description / error", "ReactNode", "Read with the input (aria-describedby); an error also sets aria-invalid."],
      ["variant / size", "Button variants", "outline and default."],
    ],
    "A label styled as a Button over a visually hidden input, so the keyboard, the form and the accessibility tree are the browser's. Focus draws its ring on the button.",
  ),
  ui(
    "input",
    "Input",
    "Controls",
    "A single-line text field for names, identifiers and short values.",
    ["Input"],
    [
      ["aria-label / label", "string", "Pair it with Label or Field. Placeholder text is not the name."],
      ["disabled", "boolean", "Keeps the value readable."],
    ],
    "Validation belongs to the host. Field connects the label, hint and error.",
  ),
  ui(
    "textarea",
    "Textarea",
    "Controls",
    "A multi-line field for notes, prompts and messages.",
    ["Textarea"],
    [
      ["rows", "number", "Visible height. The field can grow with content in the host."],
    ],
    "Use it for text the person writes. Do not put formatted HTML in the value.",
  ),
  ui(
    "label",
    "Label",
    "Controls",
    "The visible name of a control.",
    ["Label"],
    [
      ["htmlFor", "string", "Id of the control this name belongs to."],
    ],
    "Field renders the label for you when the control has a hint or an error.",
  ),
  ui(
    "field",
    "Field",
    "Controls",
    "Connects a label, hint and error to one control.",
    ["Field"],
    [
      ["label", "ReactNode", "Visible name."],
      ["description", "ReactNode", "Hint announced with the control."],
      ["error", "ReactNode", "Shown after a failed check. Marks the control invalid."],
      ["children", "(props) => ReactNode", "Receives id and aria attributes to spread onto the control."],
    ],
    "The host decides when a value is invalid. Field only wires the accessible relationship.",
  ),
  ui(
    "checkbox",
    "Checkbox",
    "Controls",
    "A binary choice that can sit in a form or a selection list.",
    ["Checkbox"],
    [
      ["checked", "boolean", "Controlled state."],
      ["onCheckedChange", "(checked) => void", "Called when the person toggles it."],
    ],
    "The label is a neighbour, not text inside the checkbox.",
  ),
  ui(
    "switch",
    "Switch",
    "Controls",
    "An immediate on or off setting.",
    ["Switch"],
    [
      ["checked", "boolean", "Current setting."],
      ["onCheckedChange", "(checked) => void", "Called when the setting changes."],
    ],
    "Use a switch for something that takes effect now. Use a checkbox when the change is saved with the rest of a form.",
  ),
  ui(
    "select",
    "Select",
    "Controls",
    "A closed list of options.",
    ["Select", "SelectTrigger", "SelectValue", "SelectContent", "SelectItem"],
    [
      ["defaultValue", "string", "Initial selected value."],
      ["value", "string", "Selected item value on SelectItem."],
    ],
    "NativeSelect remains for pages that need a native control inside a plain form. This select is the styled list.",
  ),
  ui(
    "dialog",
    "Dialog",
    "Overlays",
    "A modal task with a title, an explanation and explicit actions.",
    ["Dialog", "DialogTrigger", "DialogContent", "DialogHeader", "DialogTitle", "DialogDescription", "DialogBody", "DialogFooter", "DialogActions", "DialogClose"],
    [
      ["open", "boolean", "Controlled open state."],
      ["onOpenChange", "(open) => void", "Fires on open and dismiss. Escape during an IME composition does not close the dialog."],
      ["DialogContent size", "default | wide | settings | full-narrow", "default is 32rem, wide 46rem, settings 62 by 42rem (72 by 48 from 100rem). Wide, settings and full-narrow are the whole screen below 48rem."],
      ["DialogContent close", "corner | footer", "corner is the X; footer draws no X and puts a Close button first in the DialogFooter (showCloseButton on DialogFooter is shadcn's name for it)."],
      ["DialogContent padding / keepMounted", "none / boolean", "padding=none removes the padding; keepMounted keeps the dialog in the DOM, hidden, while it is closed."],
      ["DialogBody scroll / padding", "boolean / none", "A DialogBody as a direct child of DialogContent gives a fixed header, a body that is the only scroller and a fixed footer. scroll=false lets the content scroll itself (a settings rail and panels)."],
      ["DialogActions", "children", "Portals the actions into the footer from a stateful child (a form under the body), after Close. Nothing renders until the footer has mounted."],
    ],
    "Focus moves into the dialog and returns to the trigger on Escape. The title names the task. Under 34rem the footer wraps: the secondary buttons share rows and the ink action, last as in the tab order, takes the full bottom row; every button is 44 px. Keep the header to the title and put the description first in the body: a phone in landscape or at a large text size then keeps room for the body. A body with no focusable content should be given tabIndex 0 and a name.",
  ),
  ui(
    "alert-dialog",
    "Alert dialog",
    "Overlays",
    "A confirmation for a destructive or hard-to-undo action.",
    ["AlertDialog", "AlertDialogTrigger", "AlertDialogContent", "AlertDialogTitle", "AlertDialogCancel", "AlertDialogAction"],
    [
      ["open", "boolean", "Controlled open state."],
    ],
    "The confirm button names the consequence. Cancel is present and is not the primary action.",
  ),
  ui(
    "sheet",
    "Sheet",
    "Overlays",
    "A side panel for filters and secondary tasks.",
    ["Sheet", "SheetTrigger", "SheetContent", "SheetHeader", "SheetTitle", "SheetDescription", "SheetBody"],
    [
      ["SheetContent side", "left | right", "Which edge the panel uses."],
      ["Sheet modal", "boolean | trap-focus", "true (default): scrim, focus trap, inert page. false: a drawer beside the page, with no scrim and no trap; an outside press does not close it, Escape and the close control do. Base UI reads modal on the root, so it is set on Sheet and SheetContent follows."],
      ["SheetContent padding / keepMounted", "none / boolean", "padding=none for content that draws its own; keepMounted keeps it mounted while closed."],
    ],
    "Sheet is the dialog primitive anchored to an edge; modal by default it traps focus. A non-modal sheet is for tools that stay open while people work in the page.",
  ),
  ui(
    "dropdown-menu",
    "Dropdown menu",
    "Overlays",
    "A small list of actions for one record.",
    ["DropdownMenu", "DropdownMenuTrigger", "DropdownMenuContent", "DropdownMenuItem"],
    [
      ["variant", "default | destructive", "destructive marks a dangerous item."],
      ["DropdownMenuContent keepMounted", "boolean", "Keep the menu in the DOM, hidden, while it is closed."],
    ],
    "Open it from a button that names the record. Do not hide the only primary action in the menu.",
  ),
  ui(
    "tooltip",
    "Tooltip",
    "Overlays",
    "A short name for an icon button.",
    ["TooltipProvider", "Tooltip", "TooltipTrigger", "TooltipContent"],
    [
      ["children", "ReactNode", "The trigger and the tooltip content."],
    ],
    "The tooltip repeats a name that is also available to assistive tech. It is not the only label.",
  ),
  ui(
    "hover-card",
    "Hover card",
    "Overlays",
    "A preview of a person, file or citation.",
    ["HoverCard", "HoverCardTrigger", "HoverCardContent"],
    [
      ["open", "boolean", "Controlled open state."],
    ],
    "The same content must be reachable from the keyboard, not only from hover.",
  ),
  ui(
    "status-popover",
    "Status popover",
    "Overlays",
    "A one-sentence status in a toolbar or header: an icon, or an icon and a word, that opens a popover with what to do about it.",
    ["StatusPopover"],
    [
      ["title / description", "string", "The popup's name and the sentence. An icon trigger is named \"title: description\"; with a label, \"title: label\"."],
      ["icon / label", "ReactNode / string", "The glyph should change with the state; label adds a visible word."],
      ["attention", "boolean | warning | danger", "Tints the trigger with a status ink. true is danger. Never the only signal."],
      ["compact / keepMounted", "boolean", "compact hides the label visually and keeps it in the name; keepMounted keeps the popover in the DOM while closed."],
    ],
    "It is a popover, not a modal and not a tooltip: Base UI names the popup by its title and Escape returns focus to the trigger. children is what a person can do about it, usually a button.",
  ),
  ui(
    "popover",
    "Popover",
    "Overlays",
    "A small anchored panel for one extra choice.",
    ["Popover", "PopoverTrigger", "PopoverContent"],
    [
      ["open", "boolean", "Controlled open state."],
      ["PopoverContent keepMounted", "boolean", "Keep the popover in the DOM, hidden, while it is closed (also on DropdownMenuContent)."],
    ],
    "Use a dialog when the task has a title and a submit action. Use a popover for a short anchored choice.",
  ),
  ui(
    "table",
    "Table",
    "Collections",
    "A data table with a caption and column headers.",
    ["Table", "TableHeader", "TableBody", "TableRow", "TableHead", "TableCell"],
    [
      ["children", "ReactNode", "Caption, header and body."],
    ],
    "The table scrolls inside its region. The page itself does not scroll sideways.",
  ),
  ui(
    "tabs",
    "Tabs",
    "Collections",
    "Switch between peer views of the same subject.",
    ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
    [
      ["defaultValue", "string", "The panel shown first."],
      ["value", "string", "Matches a trigger to its panel."],
      ["Tabs orientation", "horizontal | vertical", "vertical makes a rail beside the panel: the list sits on the sidebar surface, the current row is the sidebar accent with a 2 px Stormlight bar on the inline-start edge, and the arrow keys move up and down."],
      ["TabsList scrollable", "boolean | narrow", "One line that scrolls sideways instead of wrapping: no scrollbar, snap to the tabs, and the selected tab is kept in view (the list scrolls its own box, never the page; right to left works). true is always; narrow only below 48rem of viewport."],
      ["TabsList variant", "underline | segmented", "underline by default."],
    ],
    "Each trigger names its panel. Do not use tabs for a step sequence. The indicator follows the active tab's own edge, so a list that wraps onto two rows still underlines the right one.",
  ),
  ui(
    "badge",
    "Badge",
    "Collections",
    "A short status that always has a text label.",
    ["Badge"],
    [
      ["tone", "neutral | info | success | warning | danger", "Color is paired with the word."],
      ["variant", "soft | outline | solid", "soft for status, outline for facts such as a license or version, solid for a count that must stand out."],
      ["dot", "boolean | hollow", "A square marker before the text, like one pixel of the dither. hollow is an outline dot for an archived or inactive item."],
      ["dotColor", "string", "Colours the dot alone with any CSS colour (var(--label-tone)); it sets --fui-badge-dot."],
      ["truncate", "boolean", "The tag shrinks to its container and cuts long text with an ellipsis; the full text goes to the title. --fui-badge-max caps the width."],
      ["--fui-badge-solid / --fui-badge-ink", "CSS properties", "Public. A tag whose colour is data sets --fui-badge-solid (tint, hairline, dot) and, if needed, --fui-badge-ink (text) on the badge itself (a class or style, not an ancestor); tones only set their defaults."],
    ],
    "A small tag with 3 px corners, never a pill. Color is not the only signal: the text says what the status is. A data colour tints the tag while the ink stays neutral, so the name reads on any colour.",
  ),
  ui(
    "card",
    "Card",
    "Collections",
    "A bounded summary of one subject.",
    ["Card", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    [
      ["children", "ReactNode", "Header, content and optional footer."],
    ],
    "A card is a section, not a clickable surface, unless the host adds one action.",
  ),
  ui(
    "alert",
    "Alert",
    "Collections",
    "A status that stays on the page.",
    ["Alert", "AlertTitle", "AlertDescription", "AlertAction"],
    [
      ["variant", "default | info | success | warning | destructive", "destructive announces an error."],
      ["layout", "stacked | inline", "inline is a slim notice for the top of a page or pane: from 48rem of its own width the title and description share a line and the action sits at the end; narrower it stacks. It fills its container."],
    ],
    "Say what happened and what the person can do. A healthy connection stays quiet. Use the inline layout for a one-off notice, never for status that refreshes periodically.",
  ),
  ui(
    "separator",
    "Separator",
    "Collections",
    "A visual break between groups.",
    ["Separator"],
    [
      ["orientation", "horizontal | vertical", "Direction of the rule."],
    ],
    "A separator is decorative. Headings name the groups.",
  ),
  ui(
    "skeleton",
    "Skeleton",
    "Collections",
    "A placeholder while the first response is still loading.",
    ["Skeleton"],
    [
      ["className", "string", "Set the height and width of the placeholder."],
    ],
    "Use a skeleton for the first load. A later refresh keeps the last value and says when it is stale.",
  ),
  ui(
    "progress",
    "Progress",
    "Collections",
    "How far a known task has gone.",
    ["Progress"],
    [
      ["value", "number", "Current amount."],
      ["max", "number", "Completed amount. Defaults to 1 or 100 depending on the host."],
    ],
    "If the duration is unknown, use Spinner instead of a bar stuck at an invented percent.",
  ),
  ui(
    "combobox",
    "Combobox",
    "Collections",
    "A text field that filters a list of known values.",
    ["Combobox"],
    [
      ["items", "string[]", "Values the field can suggest."],
    ],
    "The input keeps its accessible name. Empty results say that nothing matched.",
  ),
  ui(
    "collapsible",
    "Collapsible",
    "Collections",
    "A disclosure for reasoning, sources or a long detail.",
    ["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
    [
      ["defaultOpen", "boolean", "Start expanded when the detail is the point of the screen."],
    ],
    "The trigger names what is hidden. The content stays in the tab order when open.",
  ),
  ui(
    "scroll-area",
    "Scroll area",
    "Collections",
    "A region that scrolls without moving the page.",
    ["ScrollArea"],
    [
      ["children", "ReactNode", "The content taller than the region."],
    ],
    "The region has an accessible name when it is the only way to reach the content.",
  ),
  ui(
    "navigation-menu",
    "Navigation menu",
    "Navigation",
    "The top-level links of a site, with one panel of related links.",
    ["NavigationMenu", "NavigationMenuList", "NavigationMenuItem", "NavigationMenuTrigger", "NavigationMenuContent", "NavigationMenuLink"],
    [
      ["href", "string", "Destination of a link."],
    ],
    "Marketing pages can use this menu. They do not become a WorkspaceShell.",
  ),
  ui(
    "sidebar",
    "Sidebar",
    "Navigation",
    "The persistent navigation of an operational app.",
    ["SidebarProvider", "SidebarMenu", "SidebarMenuItem", "SidebarMenuButton", "SidebarMenuBadge"],
    [
      ["isActive", "boolean", "Marks the current destination (aria-current page, a fill and a 2 px Stormlight bar)."],
      ["SidebarMenuButton size", "default | sm | lg | touch", "touch is a navigation row: a 44 px target around a 40 px band, the focus ring inside the band, muted icons. Nested rows take depth (0 to 4)."],
      ["SidebarMenuButton render", "ReactElement", "Pass the host's link: render={<a href />} or a router Link."],
      ["SidebarMenuBadge", "span", "Inside the button it is a count in the row and part of the link's name (a screen reader hears Inbox 12); beside it, it floats over the end of the button."],
      ["SidebarProvider keyboardShortcut", "string | false", "The key that toggles the sidebar with Ctrl or Command (default b). It is ignored while a person types in a field or an editor, where Ctrl+B is Bold. false turns it off."],
      ["SidebarProvider persist", "boolean", "false writes no sidebar_state cookie, for a host that keeps the state."],
      ["Sidebar labels / SidebarTrigger label / SidebarRail label", "string", "The names screen readers hear (English by default): translate them."],
    ],
    "Menu rows work without a SidebarProvider: a list of navigation links renders expanded with no shell around it. Below 768px the full sidebar shell becomes a sheet. The host owns routing.",
  ),
  ui(
    "command",
    "Command",
    "Navigation",
    "The command palette. Search a short list of real destinations.",
    ["Command", "CommandInput", "CommandList", "CommandEmpty", "CommandGroup", "CommandItem", "CommandDialog", "Kbd"],
    [
      ["open", "boolean", "CommandDialog open state."],
    ],
    "fabrials.com and the ai-relay console open this with Ctrl or Command K. Radiant uses Command to choose a model and does not add a second palette. The dialog has 6 px corners, the overlay shadow and one variable for its top and its maximum height; the selected row has the accent fill and the 2 px Stormlight bar. CommandDialog does not wrap its children: put a Command inside.",
  ),
  ui(
    "command-trigger",
    "Command launcher",
    "Navigation",
    "The launcher of a palette, and the rows of a palette that is not cmdk.",
    ["CommandTrigger", "CommandOptionList", "CommandOption"],
    [
      ["CommandTrigger label / name / icon", "ReactNode / string", "The visible text; the accessible name when it must say more (it should contain the label); a decorative icon (a magnifier by default)."],
      ["CommandTrigger keys / sequence / shortcut", "string[] / boolean / string | false", "Key caps, \"mod\" being the main modifier resolved after hydration (Ctrl on the server). aria-keyshortcuts is derived from them (Control+K Meta+K) and constant; false omits it. sequence shows \"G then K\" and derives none, because aria-keyshortcuts cannot express steps."],
      ["CommandTrigger compact", "boolean", "Icon only at any width. Inside a container named command narrower than 12rem (the command slot of AppHeader) it is icon-only without the prop. The key hint hides on coarse pointers."],
      ["CommandOption active / disabled", "boolean", "active is the virtual focus (aria-selected, data-active): accent fill and a 2 px Stormlight bar. disabled sets aria-disabled and mutes the label but stays selectable, so activating it can say why."],
      ["CommandOption icon / label / detail / group / reason / keys", "ReactNode", "The slots. Below 32rem of list width the label takes its own line, then detail and group, then the reason."],
    ],
    "The launcher is a secondary button with the 3:1 control boundary, because it looks like the field it opens. The option list is a tabIndex -1 listbox: the input that drives it holds the focus and names the active row with aria-activedescendant. Set --fui-command-list-max (20rem by default) to none when a parent gives it a height.",
  ),
  ui(
    "kbd",
    "Kbd",
    "Navigation",
    "A flat hint for a keyboard shortcut.",
    ["Kbd", "KbdGroup", "useModifierKey"],
    [
      ["children", "ReactNode", "The key label, such as Ctrl or K."],
      ["Kbd mod", "boolean", "Prints the main modifier of this device: Ctrl on the server and at first paint, the command key on Apple devices right after hydration."],
      ["KbdGroup sequence", "boolean", "Keys pressed one after the other: the separator word goes between them, muted."],
      ["KbdGroup separator", "ReactNode", "The word between keys of a sequence (default then). It is copy: translate it."],
      ["useModifierKey()", "() => Ctrl | ⌘", "The same value for a label you build yourself. The shortcut itself should test ctrlKey or metaKey."],
    ],
    "This is a flat label. It is not a 3D keycap. Show the modifier with mod or useModifierKey so the markup never mismatches on hydration.",
  ),
  ui(
    "button-group",
    "Button group",
    "Composition",
    "Related actions that belong to one choice.",
    ["ButtonGroup", "Button"],
    [
      ["orientation", "horizontal | vertical", "Direction of the group."],
    ],
    "Group actions that change the same subject. Do not group unrelated buttons just to save space.",
  ),
  ui(
    "input-group",
    "Input group",
    "Composition",
    "A field with an addon or an action attached to it.",
    ["InputGroup", "InputGroupAddon", "InputGroupInput"],
    [
      ["children", "ReactNode", "Addon and the input."],
    ],
    "The input still has its own accessible name. The addon is not a placeholder.",
  ),
  ui(
    "carousel",
    "Carousel",
    "Composition",
    "A sideways list of peer items, such as citations.",
    ["Carousel", "CarouselContent", "CarouselItem", "CarouselPrevious", "CarouselNext"],
    [
      ["orientation", "horizontal | vertical", "Scroll direction."],
    ],
    "Previous and next are buttons. Arrow keys move the list when it has focus.",
  ),
  ui(
    "spinner",
    "Spinner",
    "Composition",
    "An indeterminate wait.",
    ["Spinner"],
    [
      ["aria-label", "string", "Defaults to Loading."],
    ],
    "The animation stops under reduced motion. Pair a long wait with text that says what is happening.",
  ),
  ui(
    "toaster",
    "Toaster",
    "Composition",
    "A short confirmation that does not move the page.",
    ["Toaster", "toast"],
    [
      ["toast", "(message) => void", "Shows one notice."],
    ],
    "Mount Toaster once. Use a toast for a completed action. Keep errors that need a decision on the page.",
  ),
  ui(
    "number-ticker",
    "Number ticker",
    "Metrics",
    "A total that counts to the current value.",
    ["NumberTicker"],
    [
      ["value", "number", "The number to show."],
      ["prefix / suffix", "string", "Unit or currency around the digits."],
    ],
    "Reduced motion jumps to the final value. A screen-reader string carries the same number. Blur is off.",
  ),
  ui(
    "series-chart",
    "Series chart",
    "Metrics",
    "A bar or line chart for one shared series contract.",
    ["SeriesChart"],
    [
      ["data", "record[]", "Rows of values."],
      ["xKey", "string", "Category field."],
      ["series", "{ key, label }[]", "The measures to draw."],
      ["kind", "bar | line", "Bar for a mix, line for a value over time."],
      ["caption", "string", "Names the chart for the accessible table."],
    ],
    "The legend can hide a series or show only one. An accessible table repeats the values. Decorative sparklines are not this chart.",
  ),
  ui(
    "workspace-shell",
    "Workspace shell",
    "Patterns",
    "Navigation, a header slot and the main task.",
    ["WorkspaceShell"],
    [
      ["navigation", "ReactNode", "The product's nav."],
      ["header", "ReactNode", "Tools for the current page."],
      ["children", "ReactNode", "The task."],
    ],
    "The host owns routes, the active item, authentication and window chrome. Mail keeps its own panes. Marketing pages do not use this shell.",
  ),
  ui(
    "page-header",
    "Page header",
    "Patterns",
    "The name of the page, a one-line description and the primary action.",
    ["PageHeader"],
    [
      ["title", "ReactNode", "Page heading."],
      ["description", "ReactNode", "What this page is for."],
      ["actions", "ReactNode", "The primary action."],
      ["headingLevel", "1 | 2 | 3 | 4", "The heading element (h1 by default). The look is the page title's at every level."],
      ["headingRef / headingProps", "Ref / { tabIndex, id, data-* }", "For code that moves focus to the heading after a route or tool change: give it tabIndex -1. A focused heading shows a ring."],
    ],
    "One page heading. Put the action next to the task it performs.",
  ),
  ui(
    "section-header",
    "Section header",
    "Patterns",
    "The name of a section inside a page.",
    ["SectionHeader"],
    [
      ["title", "ReactNode", "Section heading."],
      ["description", "ReactNode", "Optional supporting line."],
      ["actions", "ReactNode", "Actions for this section only."],
      ["headingLevel", "1 | 2 | 3 | 4", "The heading element (h2 by default). The look is the section title's at every level."],
      ["headingRef / headingProps", "Ref / { tabIndex, id, data-* }", "For code that moves focus to the heading; tabIndex -1 makes it focusable and it shows a ring."],
    ],
    "Use it before inventing another heading style.",
  ),
  ui(
    "collection-toolbar",
    "Collection toolbar",
    "Patterns",
    "Search, filters and actions for one collection.",
    ["CollectionToolbar"],
    [
      ["search", "ReactNode", "The search field."],
      ["filters", "ReactNode", "Filters for this collection."],
      ["actions", "ReactNode", "Actions that apply before a selection."],
    ],
    "Keep filters next to the collection they change.",
  ),
  ui(
    "bulk-actions",
    "Bulk actions",
    "Patterns",
    "Actions that appear after the person selects rows.",
    ["BulkActions"],
    [
      ["count", "number", "Selected rows. The bar is hidden at zero."],
      ["children", "ReactNode", "The actions."],
      ["keepMounted", "boolean", "Keep the region at zero: the actions are hidden, the status stays (visually hidden) so the first selection is announced."],
    ],
    "Show the bar only after selection begins. The status names the count.",
  ),
  ui(
    "state-panel",
    "State panel",
    "Patterns",
    "Loading, empty, error, stale and offline states.",
    ["StatePanel"],
    [
      ["state", "loading | empty | error | stale | offline | success", "Which state this is."],
      ["title", "ReactNode", "What happened."],
      ["description", "ReactNode", "What the person can do."],
      ["actions", "ReactNode", "The recovery action."],
      ["size", "md | sm", "sm is 16 px of padding, for a drawer, popover, sidebar or list slot; the icon and text are the same."],
      ["variant", "panel | inline", "inline has no border and no tint (an overlay or palette); the icon still carries the state."],
      ["fill", "boolean", "Takes the height of a region that has one and centres the content (an empty reader pane)."],
      ["align", "start | center", "Where the icon and text sit."],
    ],
    "A stale observation is not shown as a fresh value. A configured connection is not proof that it can be reached.",
  ),
  ui(
    "confirm-dialog",
    "Confirm dialog",
    "Overlays",
    "Confirm first, then run an async action with a pending state and an inline error.",
    ["ConfirmDialog", "ConfirmActionButton", "ConfirmProvider", "useConfirm"],
    [
      ["title", "ReactNode", "What will happen."],
      ["description", "ReactNode", "What it affects."],
      ["details", "ReactNode", "Optional list of the affected records."],
      ["confirmLabel", "ReactNode", "Names the action."],
      ["pendingLabel", "ReactNode", "Shown while the action runs."],
      ["destructive", "boolean", "Uses the destructive confirm button."],
      ["onConfirm", "() => Promise", "Resolve { ok: false, error } or throw to keep the dialog open with the error."],
      ["open", "boolean", "ConfirmDialog is controlled with onOpenChange. ConfirmActionButton owns its trigger and state."],
      ["finalFocus", "false | ref | (closeType, outcome) => element", "Where focus lands on close; outcome is confirmed or dismissed. A confirmed action that removes its trigger names the element that now holds the result; Cancel and Escape still return to the trigger."],
      ["useConfirm()", "(options) => Promise<boolean>", "Awaitable: true on confirm, false for Cancel, Escape, the backdrop or an unmounted provider. Mount ConfirmProvider once; without it the function is window.confirm. Questions asked while one is open wait their turn."],
    ],
    "The confirm button shows a spinner while the action runs and cannot be pressed twice. A failure stays inline and keeps the dialog open; success closes it. The host performs the action. useConfirm is for flows that can await; a guard that must answer synchronously (back, forward, unload) keeps window.confirm.",
  ),
  ui(
    "filter-chip",
    "Filter chip",
    "Controls",
    "An active filter with a one-click clear, as a link or a button.",
    ["FilterChip"],
    [
      ["label", "string", "The filter name."],
      ["value", "string", "Its current value."],
      ["href", "string", "Renders a link that clears the filter."],
      ["onRemove", "() => void", "Renders a button that clears the filter."],
      ["clearLabel", "string", "Accessible name of the clear action."],
    ],
    "Pass either href or onRemove. Long values truncate inside the chip. The target is 44px on touch.",
  ),
  ui(
    "truncated-text",
    "Truncated text",
    "Composition",
    "A single line that shows its full text in a tooltip only when it is cut off.",
    ["TruncatedText"],
    [
      ["children", "string", "The full text."],
      ["side", "top | right | bottom | left", "Where the tooltip opens. sideOffset and align refine it."],
    ],
    "The tooltip never intercepts clicks on row actions next to it. Text that fits has no tooltip.",
  ),
  ui(
    "shimmer-text",
    "Shimmer text",
    "Composition",
    "A CSS-only loading label with a light sweep.",
    ["ShimmerText"],
    [
      ["children", "string", "The label."],
      ["as", "ElementType", "Element to render. Defaults to p."],
      ["duration", "number", "Sweep length in seconds. spread sets the highlight width."],
    ],
    "Use it for a short pending label, not for content. Under reduced motion it is plain muted text.",
  ),
  ui(
    "file-thumb",
    "File thumbnail",
    "Collections",
    "An image preview or a file-type tile for file lists.",
    ["FileThumb", "fileTypeLabel"],
    [
      ["src", "string | null", "Image to preview. A broken image falls back to the tile."],
      ["mime", "string | null", "Labels the tile with filename, for example PDF or CSV."],
      ["icon", "ReactNode", "Replaces the default tile icon."],
      ["size", "number", "Square size in pixels."],
      ["alt", "string", "Text alternative for the preview."],
    ],
    "fileTypeLabel returns the same short label for use elsewhere. The host decides which URLs are safe to preview.",
  ),
  ui(
    "recency-groups",
    "Recency groups",
    "Collections",
    "Groups a history by Today, Yesterday, Previous 7 days, Previous 30 days, then month.",
    ["groupByRecency", "RECENCY_LABELS", "TruncatedText"],
    [
      ["items", "readonly T[]", "Records to group, in the order to keep inside each group."],
      ["getDate", "(item) => Date", "Reads the date of one record. Strings and numbers work too."],
      ["now", "Date", "Reference time. Defaults to the current time."],
      ["options", "object", "timeZone, locale and label overrides."],
    ],
    "A helper, not a component. Buckets follow calendar days in the given time zone. The host renders the groups.",
  ),
  ui(
    "settings-section",
    "Settings section",
    "Patterns",
    "A settings row with the title, description and status on the left and the controls on the right.",
    ["SettingsSection"],
    [
      ["title", "ReactNode", "Section heading."],
      ["description", "ReactNode", "What the setting changes."],
      ["status", "ReactNode", "A badge such as Saved, Loading or Error."],
      ["headingLevel", "1 | 2 | 3 | 4", "Heading level for the title (2 by default)."],
      ["headingRef / headingProps", "Ref / { tabIndex, id, data-* }", "For code that moves focus to the heading. The section is named by the id the heading has, so a custom id keeps aria-labelledby right."],
      ["layout", "auto | stacked", "auto puts the help (13rem) beside the controls from 36rem of the section's own width and stacks below it, in a sheet, a dialog or a page alike. stacked is always one column."],
      ["children", "ReactNode", "The controls."],
    ],
    "The section is the size container, so it takes its width from its parent: keep it in a block, grid or column flex parent, not a content-sized row. Saving and validation belong to the host.",
  ),
  ui(
    "suggestion-card",
    "Suggestion card",
    "Patterns",
    "Empty-state prompts in a grid on wide screens and a scroll row on narrow ones.",
    ["SuggestionCard", "SuggestionGrid"],
    [
      ["title", "ReactNode", "The prompt."],
      ["description", "ReactNode", "A short explanation. Clamps at two lines."],
      ["icon", "ReactNode", "Optional leading icon."],
      ["onClick", "() => void", "Each card is a button and accepts disabled."],
      ["columns", "1 | 2 | 3 | 4", "SuggestionGrid columns on wide screens."],
    ],
    "Give the grid an aria-label. What a suggestion does is up to the host.",
  ),
  ui(
    "moon-phase",
    "Moon phase",
    "Effects",
    "The moon at a given phase, optionally cycling, with rare moon types and lunar phase helpers.",
    ["MoonPhase", "MOON_VARIANTS", "pickMoonVariant", "lunarPhase", "lunarPhaseName"],
    [
      ["phase", "number", "0 new, 0.5 full, 1 new again."],
      ["animate", "boolean", "Cycles through the phases over cycleMs."],
      ["size", "number | string", "Width and height."],
      ["halo", "boolean", "Glow drawn from the lit side only, so it follows the shadow."],
      ["variant", "id | \"random\"", "Moon type. Random rolls a weighted type at each new moon."],
      ["caption", "boolean", "Shows the type and rarity while it is visible."],
      ["label", "string", "Accessible name. Without it the moon is decorative."],
      ["lunarPhase", "(date) => number", "Phase for a date. lunarPhaseName names it."],
    ],
    "Types: earthshine (crescents), moon halo, harvest, supermoon, micromoon, blue, blood and the legendary super blood moon; full-moon types only show near full. Server code imports the helpers from @fabrials/ui/moon. MoonPhase and Starfield are the only sanctioned glow and continuous motion in Fabrials UI, for sign-in and landing surfaces only. The cycle stops under reduced motion.",
  ),
  ui(
    "starfield",
    "Starfield",
    "Effects",
    "A decorative star layer behind sign-in and landing content.",
    ["Starfield"],
    [
      ["twinkle", "boolean", "Slow twinkle on the far layer."],
      ["className", "string", "Positioning overrides. It fills a positioned parent."],
    ],
    "Hidden from assistive technology and never takes pointer events. Like MoonPhase, it is only for sign-in and landing surfaces, and the twinkle stops under reduced motion.",
  ),
  aiUi(
    "chat-message",
    "Chat message",
    "A user or assistant turn with copy, edit, retry and timestamp actions.",
    ["ChatMessage", "MessageActions", "MessageAction", "CopyMessageAction", "MessageTimestamp"],
    [
      ["from", "ChatRole", "user, assistant or system. User turns sit in a bubble."],
      ["actions", "ReactNode", "MessageActions for this turn."],
      ["pinActions", "boolean", "Keeps actions visible instead of revealing them on hover and focus."],
      ["text", "string", "CopyMessageAction writes it to the clipboard. A function works too."],
      ["dateTime", "string", "MessageTimestamp shows label with detail in a tooltip."],
    ],
    "Presentational. The host supplies the rendered content, including its markdown renderer, and decides what edit and retry do.",
  ),
  aiUi(
    "chat-composer",
    "Chat composer",
    "The message field with tools, attachments, send and stop.",
    ["ChatComposer", "ComposerToggle", "ComposerButton"],
    [
      ["value", "string", "Controlled with onValueChange. defaultValue works uncontrolled."],
      ["onSubmit", "(value) => void", "Enter sends; Shift+Enter adds a line."],
      ["status", "ChatComposerStatus", "ready, submitting or streaming. Streaming turns send into stop, which calls onStop."],
      ["tools", "ReactNode", "ComposerButton and ComposerToggle on the left. trailing holds voice input."],
      ["attachments", "ReactNode", "Attachments shown above the field."],
      ["onPasteFiles", "(files) => void", "Receives pasted files. Backspace in an empty field calls the remove-last handler."],
    ],
    "Presentational. The host sends the message, uploads pasted files and owns the tool state.",
  ),
  aiUi(
    "code-block",
    "Code block and markdown",
    "Answer styles for rendered markdown and a code block with copy and download.",
    ["CodeBlock"],
    [
      ["code", "string", "Raw code used by copy and download."],
      ["language", "string", "Shown in the header and used for the download name."],
      ["children", "ReactNode", "Highlighted lines. Without it the raw code is shown."],
      ["lineNumbers", "boolean", "Numbers each line."],
      ["download", "boolean", "Adds a download action named after filename. A function replaces it."],
      ["fui-markdown", "class", "Styles headings, lists, quotes, tables and code, including Streamdown data-streamdown output."],
    ],
    "Presentational. The host supplies the markdown renderer and syntax highlighting; these pieces only style the result.",
  ),
  aiUi(
    "citations",
    "Citations and sources",
    "Numbered citation chips linked to a list of source cards.",
    ["CitationProvider", "CitationChip", "Sources", "SourceCard", "SourceFavicon"],
    [
      ["sources", "CitationSource[]", "CitationProvider sources by number. Hovering a chip highlights its card."],
      ["number", "number", "CitationChip number and href. Shows a source preview."],
      ["Sources", "component", "Collapsible list of SourceCard links."],
      ["faviconUrl", "(url) => string", "Host resolver for favicons. Without it a letter mark is shown."],
    ],
    "Presentational. The host supplies the sources and any favicon service; nothing is fetched by these components.",
  ),
  aiUi(
    "activity-disclosure",
    "Activity disclosure",
    "Collapsible reasoning, search steps and tool activity inside an answer.",
    ["ActivityDisclosure", "ActivityIcon", "ReasoningDisclosure", "SearchStepsDisclosure"],
    [
      ["streaming", "boolean", "ReasoningDisclosure shows Thinking, then Thought for durationSeconds."],
      ["phase", "SearchPhase", "For search steps: searching, reading or done, with steps and sourceCount."],
      ["live", "boolean", "ActivityDisclosure for any other activity. ActivityIcon marks the live state."],
      ["open", "boolean", "Controlled open state. defaultOpen works uncontrolled."],
    ],
    "Presentational. The host maps its stream events to these props. Live indicators stop under reduced motion.",
  ),
  aiUi(
    "attachments",
    "Attachments",
    "Files attached to a message, inline, as a grid or as a list.",
    ["Attachments", "AttachmentChip"],
    [
      ["items", "AttachmentItem[]", "id, name, mediaType, url, size, status and error."],
      ["variant", "inline | grid | list", "Layout."],
      ["onRemove", "(id) => void", "Shows a remove button on each file."],
      ["empty", "ReactNode", "Shown when there are no files."],
    ],
    "Presentational. The host uploads the files and reports uploading and error states.",
  ),
  aiUi(
    "voice-input",
    "Voice input",
    "A microphone button that records a clip and hands it to the host for transcription.",
    ["VoiceInputButton", "VoiceInputButtonView"],
    [
      ["onRecorded", "(blob) => Promise", "Host transcription. Resolves to the text."],
      ["onTranscript", "(text) => void", "Receives the text to insert."],
      ["maxDurationMs", "number", "Stops recording at this length."],
      ["showLevel", "boolean", "Shows the input level while recording."],
      ["status", "VoiceInputStatus", "idle, requesting, recording, transcribing or error. The stateless view uses it for custom recorders."],
    ],
    "Presentational. The microphone is only requested after a press. The host supplies transcription; nothing is sent by the component.",
  ),

  // ---------------------------------------------------------------- 0.5–0.7 additions
  ui(
    "dither-scene",
    "Dither scene",
    "Brand",
    "The Highstorm storm front behind a landing hero or a sign-in page.",
    ["DitherScene"],
    [
      ["variant", "hero | full", "hero enters from the right of the box; full covers it, for sign-in."],
      ["reveal", "number", "Milliseconds for the one-time roll-in on first paint; 0 turns it off. Skipped under reduced motion."],
      ["seed", "number", "Another storm with the same look."],
      ["cell", "number", "CSS pixels per dither dot (2 to 4)."],
    ],
    "Absolute: give the parent position: relative and keep text on the calm side or on a solid surface. The ramp fades into --fui-dither-bg, else --background. Painted once; no loop.",
  ),
  ui(
    "dither-band",
    "Dither band",
    "Brand",
    "A thin storm band that signs a section or page heading.",
    ["DitherBand"],
    [
      ["seed", "number", "Another band with the same look."],
      ["--fui-band-height", "CSS length", "Height, 4.5rem by default."],
    ],
    "At most one per view. On a card, set --fui-dither-bg: var(--card) so the band fades into it.",
  ),
  ui(
    "dither-gem",
    "Dither gem",
    "Brand",
    "A cut gem filled with dithered light: the product mark in navigation, lists and empty states.",
    ["DitherGem"],
    [
      ["gem", "GemName", "The product's gem: stormlight, heliodor, sapphire, ruby, emerald, zircon, smokestone or amethyst."],
      ["size", "number", "Box size in CSS pixels: 16, 20, 28 or 40 in interfaces, larger beside a hero."],
      ["reveal", "number", "Large marks only: fills with light once on first paint."],
    ],
    "Decorative (aria-hidden). Always pair it with the product name.",
  ),
  ui(
    "dither-canvas",
    "Dither canvas",
    "Brand",
    "The engine under the brand pieces: any brightness field, dithered onto a colour ramp.",
    ["DitherCanvas"],
    [
      ["field", "(theme, size, progress) => (u, v) => 0…1", "Brightness at each point; built again on resize and theme change."],
      ["ramp", "string[] | { light, dark }", "Colours. \"background\" as the first stop is the surface behind the canvas."],
      ["order", "brightness | ramp", "ramp keeps the order: 0 is the first colour, 1 the last."],
      ["reveal / stars / paintKey", "number / DitherStars / key", "One-time reveal, crisp stars in dark mode, repaint on new data."],
    ],
    "A backdrop: it fills its positioned parent and sits behind the content, so the parent needs position: relative and isolation: isolate (Tailwind relative isolate). Pure helpers live in @fabrials/ui/dither (paintRampField, STORM_RAMP, gemRamp, stormField, gemField). Products may add their own fields on the same engine.",
  ),
  ui(
    "product-lockup",
    "Product lockup",
    "Brand",
    "A product's name with its gem, for headers and sign-in.",
    ["ProductLockup", "FabrialsGem"],
    [
      ["product", "string", "The product name, set in Plex Sans Condensed."],
      ["gem", "GemName", "The product's gem."],
      ["tagline", "string", "Optional second line."],
      ["size", "sm | md | lg", "Scale."],
    ],
    "The gem signs the mark and nothing else; it is never a status or a button colour.",
  ),
  ui(
    "radio-group",
    "Radio group",
    "Controls",
    "One choice from a short list that stays visible.",
    ["RadioGroup", "RadioGroupItem", "Radio"],
    [
      ["defaultValue / value", "string", "The selected option."],
      ["onValueChange", "(value) => void", "Called when the choice changes."],
      ["aria-label", "string", "Names the group when there is no visible legend."],
    ],
    "Arrow keys move between options. RadioGroupItem is shadcn's name for Radio.",
  ),
  ui(
    "toggle-group",
    "Toggle group",
    "Controls",
    "A segmented choice for ranges and views.",
    ["ToggleGroup", "ToggleGroupItem"],
    [
      ["value", "string[]", "Selected items."],
      ["onValueChange", "(value: string[]) => void", "Keep at least one selected for a single choice."],
      ["size", "default | sm | lg", "Painted height 34, 26 or 40px; every size is 44px on touch and narrow screens."],
    ],
    "Use it for a view or range next to what it changes; use RadioGroup inside forms.",
  ),
  ui(
    "theme-switcher",
    "Theme switcher",
    "Controls",
    "System, light or dark, as a compact segmented control.",
    ["ThemeSwitcher"],
    [
      ["value", "system | light | dark", "The stored preference."],
      ["onValueChange", "(value) => void", "The host applies and stores it."],
      ["showLabels", "boolean", "Words next to the icons."],
      ["size", "default | sm | lg", "sm by default; lg matches the 40px controls of a settings row."],
    ],
    "The host owns storage and the class on the root element; the switcher only presents the choice.",
  ),
  ui(
    "multi-select",
    "Multi-select",
    "Controls",
    "Several values from a list, summarised in the trigger.",
    ["MultiSelect"],
    [
      ["id / label", "string", "Connects the visible label."],
      ["options", "{ value, label }[]", "The choices."],
      ["value / onValueChange", "string[] / (value) => void", "Controlled selection."],
      ["placeholder", "string", "Shown when nothing is selected, \"Any\" by default."],
    ],
    "Use it for filters. For a single value, use Select.",
  ),
  ui(
    "native-select",
    "Native select",
    "Controls",
    "The browser's own select, styled, for long lists and forms that must work without JavaScript.",
    ["NativeSelect", "NativeSelectOption", "NativeSelectOptGroup", "NativeCheckbox"],
    [
      ["name / defaultValue", "string", "Submitted with the form."],
      ["children", "NativeSelectOption | NativeSelectOptGroup", "Options, optionally grouped."],
      ["NativeCheckbox indeterminate", "boolean", "The mixed state of a select-all. It is applied as the element's property and re-applied after every render and change."],
      ["NativeCheckbox label", "ReactNode", "Puts the box in a whole-row label, a 44px target."],
    ],
    "Keeps the platform picker on phones. NativeCheckbox is the matching native checkbox; NativeRadio and NativeRadioGroup are the radios.",
  ),
  ui(
    "native-radio",
    "Native radio group",
    "Controls",
    "The browser's own radios in a fieldset with a legend, for forms that must work without JavaScript and for swatch pickers.",
    ["NativeRadioGroup", "NativeRadio"],
    [
      ["legend", "ReactNode", "The name of the group. Required."],
      ["hideLegend", "boolean", "Keeps the legend for assistive technology and hides it."],
      ["layout", "stack | grid", "grid flows the options into columns of at least 9rem."],
      ["NativeRadio label", "ReactNode", "A whole-row label, a 44px target. name and value are the form's."],
      ["disabled", "boolean", "On the group it disables every native radio."],
    ],
    "The arrow keys move within a name group natively. A Base UI RadioGroup is spans that a disabled fieldset does not disable; use these when the form must submit natively.",
  ),
  ui(
    "field-set",
    "Field set",
    "Controls",
    "Grouped form fields on a real fieldset: a titled subsection with a hairline above, and fields laid out with the house gap.",
    ["FieldSet", "FieldLegend", "FieldGroup"],
    [
      ["FieldSet disabled", "boolean", "Disables every native control inside. Base UI checkboxes and switches are not native: disable those yourself."],
      ["FieldLegend variant", "title | label", "A subsection title (16px) or a small group name (14px)."],
      ["FieldLegend divider", "boolean", "The hairline above, drawn on the legend and left out when the fieldset is the first of its container. On by default."],
      ["FieldGroup layout", "stack | columns", "columns flows fields into as many columns of at least 15rem as the container has room for."],
    ],
    "A fieldset never overflows its column (min-inline-size 0). Hide a legend the design does not show with className=\"fui-sr-only\". Field, the label-and-error wrapper, is a different piece.",
  ),
  ui(
    "toolbar",
    "Toolbar",
    "Controls",
    "One tab stop for a row of controls: Tab enters and leaves once, the arrows, Home and End move between the buttons.",
    ["Toolbar", "ToolbarGroup", "ToolbarSeparator", "ToolbarButton"],
    [
      ["Toolbar aria-label", "string", "Required: the toolbar is announced by its name. ToolbarGroup needs one too."],
      ["Toolbar variant / sticky / contain", "plain | bar / boolean / boolean", "bar is the page background between two hairlines, aligned to the page gutter, and measures its own width; sticky keeps it under the top of its scroll container."],
      ["Toolbar orientation / loopFocus", "horizontal | vertical / boolean", "Arrow keys follow the orientation; focus wraps unless loopFocus is false."],
      ["ToolbarButton label", "string", "The name, as a text node inside the button. Hidden until reveal shows it."],
      ["ToolbarButton reveal", "early | middle | late", "Shows the label from a toolbar width of 40rem, 52rem or 76rem."],
      ["ToolbarButton tier", "high | low | overflow", "low is hidden below 34rem and folds into a menu; overflow is that menu's trigger and only shows below 34rem. Hidden items leave the arrow-key order."],
      ["ToolbarButton tooltip / shortcut", "boolean | ReactNode / string | string[] | { keys, sequence? }", "As IconButton, including the sequence form."],
    ],
    "Buttons stay in the arrow order when disabled (aria-disabled, no click) so neighbours never shift under a person who is arrowing. A native text field or select inside a toolbar adds a tab stop of its own; put it next to the toolbar. Before hydration the buttons are click targets only.",
  ),
  ui(
    "disclosure",
    "Disclosure",
    "Collections",
    "A styled native details element: a 44px summary with a chevron and a count, a panel that stays in the page, no JavaScript.",
    ["Disclosure", "DisclosureSummary", "DisclosurePanel"],
    [
      ["Disclosure open / onToggle / name", "details props", "Native: name makes an exclusive group."],
      ["Disclosure revealInvalid", "boolean", "Opens itself when a field inside fails validation so the browser can focus it. On by default."],
      ["DisclosureSummary count", "ReactNode", "After the label, inside the summary: part of its name."],
      ["DisclosureSummary chevron", "end | start | none", "end turns from down to up; start points to the inline end when closed."],
      ["DisclosureSummary size", "sm | md | lg", "md is the 44px default, lg a section title, sm a quiet line with an invisible 44px target."],
    ],
    "Server-rendered exactly as it hydrates. Use Accordion for a set of exclusive animated sections and Collapsible for a trigger you control.",
  ),
  ui(
    "accordion",
    "Accordion",
    "Collections",
    "Questions and details that open in place.",
    ["Accordion", "AccordionItem", "AccordionTrigger", "AccordionContent"],
    [
      ["multiple", "boolean", "Let several items stay open."],
      ["defaultValue", "string[]", "Items open at first."],
      ["Accordion variant", "default | rows", "rows is a stack of independent tools: 44 px header rows (icon, title, tags, chevron), the open row marked like the current item, bodies that stay mounted while closed (keepMounted is on by default there)."],
      ["AccordionTrigger headingLevel / headingRef", "2 | 3 | 4 / Ref", "The level of the heading around the trigger; a ref makes the heading focusable and hands focus to the trigger."],
      ["AccordionTrigger icon / aside", "ReactNode", "aside (tags, counts) sits outside the trigger: it is not part of the name, describes the trigger, and does not make the row a bigger target. Non-interactive."],
    ],
    "Keep the answer short; long content belongs on its own page. Base UI's accordion has no arrow-key roving: each trigger is a tab stop. A row whose expansion lives in the URL is a link, not an accordion trigger.",
  ),
  ui(
    "breadcrumb",
    "Breadcrumb",
    "Navigation",
    "Where the page sits, with a way back up.",
    ["Breadcrumb", "BreadcrumbList", "BreadcrumbItem", "BreadcrumbLink", "BreadcrumbPage", "BreadcrumbSeparator", "BreadcrumbEllipsis"],
    [["BreadcrumbLink render", "ReactElement", "Pass the host's link element."]],
    "The current page is text, not a link, and carries aria-current.",
  ),
  ui(
    "pagination",
    "Pagination",
    "Navigation",
    "Pages of a long collection.",
    ["Pagination", "PaginationContent", "PaginationItem", "PaginationLink", "PaginationPrevious", "PaginationNext", "PaginationEllipsis"],
    [["isActive", "boolean", "Marks the current page."]],
    "Prefer a cursor or \"Load more\" when page numbers mean nothing to the reader.",
  ),
  ui(
    "nav-tabs",
    "Nav tabs",
    "Navigation",
    "Links styled as tabs, for the sections of one record.",
    ["NavTabs", "NavTab"],
    [
      ["label", "string", "Names the navigation."],
      ["current", "boolean", "The section on screen (aria-current=page)."],
      ["count", "number | string", "Optional count after the label."],
      ["render", "ReactElement", "The host's link element."],
    ],
    "Each tab is a URL. Use Tabs when the panels live on the same page.",
  ),
  ui(
    "description-list",
    "Description list",
    "Collections",
    "Terms and values, such as a record's properties.",
    ["DescriptionList", "DescriptionItem", "DescriptionTerm", "DescriptionDetails"],
    [["layout", "grid | stacked | auto", "Side by side, stacked, or auto: it follows the list's own width, stacked under 30rem and a 8 to 11rem term column from it (the list becomes a size container, so it must fill its parent's width)."]],
    "A configured value is not a verified one: say which it is.",
  ),
  ui(
    "avatar",
    "Avatar",
    "Collections",
    "A person or account, with initials when there is no image.",
    ["Avatar", "AvatarImage", "AvatarFallback", "avatarInitials"],
    [
      ["size", "sm | md | lg", "Scale."],
      ["avatarInitials(value, fallback?, locale?)", "string", "The fallback text: first letters of the first and last word of a name, or the first letter of an address. Grapheme-safe, upper-cased in the locale."],
    ],
    "Decorative next to a name; give it alt text when it stands alone.",
  ),
  ui(
    "file-size",
    "File size",
    "Metrics",
    "A byte count as people read it: 25 MB, 1,5 kB.",
    ["FileSize", "formatBytes"],
    [
      ["bytes", "number | null | undefined", "The count. An unknown or invalid value renders the fallback, never throws."],
      ["locale", "string", "Language of the number and unit."],
      ["formatBytes(locale, bytes)", "string", "The plain function: 1024 steps, short units, throws a RangeError for a negative or non-finite count."],
    ],
    "Tabular and unbroken, with the exact count in the title.",
  ),
  ui(
    "stat",
    "Stat",
    "Metrics",
    "One number with its change and a short trend.",
    ["Stat", "StatGroup"],
    [
      ["label / value / unit", "string", "What, how much, in what."],
      ["delta / trend", "string / up | down | flat", "The change, with an icon, not only a colour."],
      ["deltaTone", "positive | negative | neutral", "Whether up is good for this number."],
      ["sparkline / hint", "number[] / string", "Recent values and the comparison period."],
    ],
    "Tabular figures. A stale value says so in the hint.",
  ),
  ui(
    "sparkline",
    "Sparkline",
    "Metrics",
    "A small line of recent values.",
    ["Sparkline"],
    [
      ["data", "number[]", "Values in order."],
      ["label", "string", "Accessible description of the trend."],
    ],
    "Shape only; put the number next to it.",
  ),
  ui(
    "meter",
    "Meter",
    "Metrics",
    "How much of a quota or budget is used.",
    ["Meter"],
    [
      ["value / min / max", "number", "The measurement."],
      ["label / hint", "ReactNode", "What it measures and when it resets."],
      ["warnAt / dangerAt", "number", "Percent thresholds for the warning and danger inks."],
    ],
    "Use Progress for a task that finishes; Meter for a level that stays.",
  ),
  ui(
    "status-dot",
    "Status dot",
    "Metrics",
    "A state as a dot and a word.",
    ["StatusDot"],
    [
      ["tone", "neutral | info | success | warning | danger", "The state's ink."],
      ["label", "ReactNode", "The word; required, even when hidden."],
      ["pulse", "boolean", "Only for something live right now; stops under reduced motion."],
    ],
    "Colour never stands alone: the label is always there for assistive technology.",
  ),
  ui(
    "activity-strip",
    "Activity strip",
    "Metrics",
    "A row of intensity cells, like posts per day or per hour.",
    ["ActivityStrip"],
    [
      ["cells", "{ label, value, tone? }[]", "One cell per period."],
      ["caption", "string", "Required: it names the table screen readers get."],
      ["startLabel / endLabel", "string", "The ends of the range."],
      ["size", "default | lg", "Cell height."],
    ],
    "Five levels of Stormlight, or a status tone per cell.",
  ),
  ui(
    "timeline",
    "Timeline",
    "Metrics",
    "An event feed with a marker, title, time and detail.",
    ["Timeline", "TimelineItem"],
    [
      ["tone / icon", "Tone / ReactNode", "The marker."],
      ["title / time", "ReactNode", "What happened and when."],
      ["fresh", "boolean", "Highlights a live item once when it arrives."],
    ],
    "Newest first. Nothing loops.",
  ),
  ui(
    "relative-time",
    "Relative time",
    "Metrics",
    "\"3 minutes ago\" in any locale, with the full date on hover.",
    ["RelativeTime", "formatRelativeTime", "formatAbsoluteTime"],
    [
      ["date", "Date | string | number", "The moment."],
      ["locale", "string", "Language of the phrase."],
      ["absoluteFormat", "Intl.DateTimeFormatOptions | (date, now) => options", "Deterministic mode: print an absolute date, no timer. A function picks the options per date (drop the year when it is this year)."],
      ["now", "number | () => number", "The clock. A number is a fixed instant and stops the timer; a function is read at every tick (a server-anchored clock)."],
      ["timeZone", "string", "The zone dates and the title are printed in. Required when a deterministic time (absoluteFormat or a fixed now) is server-rendered; otherwise the server and the browser print different text."],
    ],
    "Refreshes while the page is visible; renders a <time> element with the exact date. With absoluteFormat or a fixed now it is deterministic; with a timeZone it hydrates without a mismatch and without suppressing the warning.",
  ),
  ui(
    "snippet",
    "Snippet",
    "Composition",
    "A command or short code with a copy button.",
    ["Snippet", "CopyButton"],
    [
      ["prompt", "string", "Shown before each line and left out of the copy, \"$\" by default."],
      ["label", "string", "Names the snippet."],
      ["copyValue", "string", "What to copy when it differs from what is shown."],
    ],
    "Long commands wrap with a hanging indent instead of scrolling.",
  ),
  ui(
    "item",
    "Item",
    "Patterns",
    "A record row for master-detail panes: one stretched target, controls above it, current and selected fills, unread weight.",
    ["ItemGroup", "Item", "ItemLink", "ItemMedia", "ItemContent", "ItemTitle", "ItemDescription", "ItemActions", "ItemControl", "ItemCheck", "ItemUnread", "ItemHeader", "ItemFooter", "ItemSeparator"],
    [
      ["ItemGroup bordered", "boolean", "A ul that is the size container its rows answer to. bordered adds a hairline above the first row; every row carries its own hairline below."],
      ["Item current", "boolean", "The record open in the detail pane: a soft Stormlight fill and a 2 px bar on the inline-start edge. Give its link current too (aria-current true)."],
      ["Item selected", "boolean", "Picked for a bulk action: the fill, no bar. A checked native checkbox inside an ItemCheck does it without this prop."],
      ["Item unread", "boolean", "The title takes weight 600. Add ItemUnread and a screen-reader word inside the link."],
      ["Item stretch", "boolean", "The link or button of the title covers the whole row and hover paints the row. Controls (ItemActions, ItemControl, ItemCheck) sit above it and stay separate targets. The focus ring is drawn inside the row so a scrolling parent never clips it."],
      ["Item variant / size", "default | outline | muted / default | sm", "outline and muted are standalone boxed items; default is a row of a list."],
      ["ItemLink current / render", "boolean | page | true / ReactElement", "The stretched target. render={<button />} makes a row that selects instead of navigating (aria-pressed says which); pass the host's router link the same way."],
      ["ItemMedia variant", "default | icon | image", "Leading visual."],
    ],
    "The root carries only the row: a 44 px minimum, a hairline below, hover, current and selected. The slots lay themselves out in a row only when they are direct children, so a host that draws its own grid inside the row adds nothing. Below 24rem of the group's width the actions wrap under the text. Never give a slot position, transform or contain: it would become the containing block of the stretched target.",
  ),
  ui(
    "app-header",
    "Application header",
    "Patterns",
    "One 56 px row for the session chrome of an app: brand, navigation, a command slot and actions.",
    ["AppHeader", "AppHeaderBrand", "AppHeaderLogo", "AppHeaderNav", "AppHeaderLink", "AppHeaderAction", "AppHeaderLabel", "AppHeaderCaret", "AppHeaderPlaceholder"],
    [
      ["brand / navigation / command / actions", "ReactNode", "The slots, in that order: the brand, the navigation, then the command slot and the actions pushed to the end."],
      ["sticky", "boolean", "Stays under the top of its scroll container."],
      ["AppHeaderLink current", "boolean", "aria-current page, full ink and a 2 px Stormlight bar on the header hairline."],
      ["AppHeaderBrand / AppHeaderLink render", "ReactElement", "Pass the host's router link."],
      ["AppHeaderLabel", "span", "Text that becomes screen-reader text below 48rem; its AppHeaderAction turns into a square icon."],
    ],
    "Modes are container queries on the header's own width: compact below 48rem, medium to 72rem, wide from there (the command slot grows to 14, 18 and 22rem), the brand name gives way at 24rem and the row wraps in two at 19rem. The command slot is the size container named command, and it has a definite width in every mode: Firefox and WebKit size the actions cluster from its content, so a slot with only a flex-basis made the header overflow. Presentational: routing, the session and the palette belong to the host.",
  ),
  ui(
    "nav-switcher",
    "Nav switcher",
    "Navigation",
    "A switcher for where you are: a trigger that names the current mailbox, workspace or project, and a popover of links.",
    ["NavSwitcher", "NavSwitcherTrigger", "NavSwitcherContent", "NavSwitcherItem", "NavSwitcherSeparator"],
    [
      ["NavSwitcher layout", "block | inline", "block fills its column with a bordered 56 px box; inline sizes to its content, for a header or a toolbar."],
      ["NavSwitcherTrigger mark / title / description / tag / label", "ReactNode / string", "The current entity. label is the screen-reader prefix (Switch mailbox); the mark is hidden from assistive technology; tag is an attention count or status."],
      ["NavSwitcherContent label / listLabel / footer", "string / ReactNode", "The popover's name, the link list's name, and a footer that stays in view under the scrolling list (a stale note, a retry)."],
      ["NavSwitcherItem current / mark / description / tag / render", "boolean / ReactNode / ReactElement", "One link. current sets aria-current, the fill, the bar and a check mark; description is a status tag inside the link and part of its name."],
    ],
    "It is a disclosure, not a menu: links stay links (a middle click opens a tab), Tab moves through them, Escape closes and focus returns to the trigger; it opens on the current link. Names wrap to two lines instead of being cut.",
  ),
  ui(
    "resizable",
    "Resizable panes",
    "Navigation",
    "Panes with draggable, keyboard-operable handles: navigation, list and reader.",
    ["ResizablePanelGroup", "ResizablePanel", "ResizableHandle", "useResizableGroupRef"],
    [
      ["ResizablePanelGroup orientation", "horizontal | vertical", "direction is accepted as shadcn's name."],
      ["ResizablePanelGroup resizeTargetMinimumSize", "{ fine, coarse }", "The hit target of a handle, 10 px for a mouse and 24 px for touch by default: bigger than the 1 px line."],
      ["ResizablePanelGroup onLayoutChanged", "(layout, meta) => void", "Save the layout here when meta.isUserInteraction is true. A double click on a handle resets the layout anywhere in its hit target; the library does not call that a user interaction, so the wrapper reports it as one."],
      ["ResizablePanel defaultSize / minSize / maxSize", "number | string", "Percent, or a string with a unit such as 18rem."],
      ["ResizableHandle label / disabled", "string / boolean", "The handle's name (give every handle one); disabled is transparent and leaves the tab order."],
    ],
    "A 1 px hairline; hover, drag and keyboard focus draw a 3 px Stormlight line. Arrow keys resize by a fixed step, Home and End jump to the limits. Built on react-resizable-panels.",
  ),
  ui(
    "site-header",
    "Site header",
    "Patterns",
    "The top bar of a public site: mark, navigation, actions and a phone menu.",
    ["SiteHeader"],
    [
      ["brand / navigation / actions", "ReactNode", "The slots."],
      ["mobileMenu", "ReactNode", "What replaces the navigation on phones."],
      ["sticky", "boolean", "Stays at the top while scrolling."],
    ],
    "Navigation that will grow groups its items in a menu (see fabrials.com's Products).",
  ),
  ui(
    "auth-layout",
    "Auth layout",
    "Patterns",
    "The sign-in page: brand, a card for the form, and an aside for the storm.",
    ["AuthLayout"],
    [
      ["brand / title / description", "ReactNode", "What the person signs in to."],
      ["actions", "ReactNode", "A corner control (appearance and language). At the inline end of the top edge, after the card in the DOM, so the first tab stop is the sign-in action."],
      ["align", "auto | start | center", "auto follows DESIGN.md: with an aside the card anchors to the inline start of its column from 1024 px, without one it centres. start anchors it at every width."],
      ["aside", "ReactNode", "Shown beside the card on wide screens; put a DitherScene variant=\"full\" in it."],
      ["footer", "ReactNode", "What the session can and cannot do."],
    ],
    "The aside is a positioning context whose surface the dither fades into.",
  ),
  ui(
    "loading",
    "Loading",
    "Composition",
    "Paints real components as their own skeleton while data loads, with no layout shift.",
    ["Loading", "placeholderText", "placeholderList", "useLoading"],
    [
      ["when", "boolean", "Shows the skeleton. The children stay mounted, so nothing moves when it turns off."],
      ["label", "string", "What assistive technology hears while it loads, e.g. Loading accounts."],
      ["placeholderText(length, seed?)", "string", "Invisible placeholder copy that wraps like real words."],
      ["placeholderList(count, make)", "T[]", "Placeholder records for lists and tables."],
      ["data-skeleton", "keep | hide | block | fill", "On any element inside: paint as usual, leave empty, one block, or a solid shape."],
    ],
    "Only paint changes (display: contents wrappers), so any width or content matches the finished view. Content is inert while loading and a status message names what loads; the pulse follows reduced motion. See the loading states guide.",
  ),
  ui(
    "code-panel",
    "Code panel",
    "Documentation",
    "A code sample with its file name, a copy button, line numbers, highlighted lines, boxed words and diff marks.",
    ["CodePanel", "highlightCode"],
    [
      ["code", "string", "The source. Copy puts exactly this on the clipboard (without removed lines)."],
      ["language", "string", "ts, tsx, js, json, bash, css or html are highlighted; anything else is plain text."],
      ["title", "ReactNode", "Usually the file path; the icon follows the language."],
      ["lineNumbers / highlightLines", "boolean / number[]", "Numbers in the gutter; 1-based lines drawn with a Stormlight edge."],
      ["addedLines / removedLines", "number[]", "Diff marks; removed lines are left out of Copy."],
      ["highlightWords", "string[]", "Boxes each occurrence, to point at a name."],
      ["children", "ReactNode", "Pre-highlighted lines (from Shiki, for instance) instead of the built-in highlighter."],
      ["bare", "boolean", "No bar; the copy button floats. For one-line snippets."],
    ],
    "The highlighter is pure and server-safe. Copy results are announced; when the clipboard refuses, the panel says how to copy by hand.",
  ),
  ui(
    "code-tabs",
    "Code tabs",
    "Documentation",
    "Several versions of one sample in one frame: languages, frameworks or files.",
    ["CodeTabs"],
    [
      ["items", "CodeTab[]", "value, label and every CodePanel option except title."],
      ["defaultValue / value / onValueChange", "string", "Uncontrolled or controlled."],
      ["label", "string", "Accessible name of the tab list."],
    ],
    "Tabs follow the Tabs keyboard model. Copy takes the open tab.",
  ),
  ui(
    "package-install",
    "Package install",
    "Documentation",
    "A command in npm, pnpm, yarn and bun. Choosing one switches every command on the page.",
    ["PackageInstall", "packageCommand"],
    [
      ["command", "string", "Without the runner: shadcn@latest add @fabrials/button."],
      ["kind", "run | install", "run uses npx, pnpm dlx, yarn dlx and bunx; install uses npm install, pnpm add, yarn add and bun add."],
      ["persistKey", "string | null", "Remembers the choice in this browser under that key; null forgets it."],
    ],
    "The saved choice is read after hydration, so the server and the first render agree on npm.",
  ),
  ui(
    "files",
    "Files",
    "Documentation",
    "A file tree: what a command creates or what a package contains. Folders open and close.",
    ["Files", "Folder", "File"],
    [
      ["Folder name / defaultOpen", "string / boolean", "Folders start closed unless defaultOpen."],
      ["File name / icon", "string / ReactNode", "The icon defaults to a plain file."],
      ["note", "ReactNode", "A short remark on the right: new, generated, a license."],
      ["highlighted", "boolean", "Marks the file the text is about."],
    ],
    "Folders are buttons with aria-expanded; indentation comes from the depth, not from nesting margins.",
  ),
  ui(
    "repo-info",
    "Repository link",
    "Documentation",
    "A GitHub repository as a compact link with its stars and forks.",
    ["RepoInfo"],
    [
      ["owner / repo", "string", "The repository; the link goes to github.com unless href is set."],
      ["stars / forks", "number | null", "Fetched and cached by the host. Unknown counts are left out, never shown as zero."],
      ["description", "ReactNode", "A line under the name."],
    ],
    "Presentational: it never calls GitHub itself, so pages stay fast and rate limits stay the host's concern.",
  ),
  aiUi(
    "provider-icon",
    "Provider icon",
    "The mark of an AI provider or coding agent.",
    ["ProviderIcon", "providerBrand"],
    [
      ["provider", "string", "openai, anthropic, xai, cursor, github, nous and more; aliases such as codex, claude and grok resolve."],
      ["size", "number", "CSS pixels, 24 by default."],
    ],
    "Third-party marks keep their own colours and shapes. Unknown providers fall back to a neutral tile.",
  ),
];

export function uiCatalogItem(slug: string): UiCatalogItem | undefined {
  return uiCatalog.find((item) => item.slug === slug);
}
